### PR TITLE
Use a specific range for a set instead of int16, 400x speedup

### PR DESCRIPTION
**Pull request by ghost**
Hello, I was just browsing recently pushed Nim repos and noticed yours, so wanted to see if I could speed it up. I've noticed that you use `int16` for a `set` which is really inefficient - Nim's built-in `sets` are bit vectors, and `set[int16]` is 8192 bytes (!), which makes your program very slow. I've changed it to a `range[0..49]` so the set now only takes 8 bytes, and the program is **~400x faster** (over 2 orders of magnitude :P) - from ~5 seconds to **10-15ms**.

I don't really know the algo itself, so maybe range needs to be bigger for bigger areas, but it's not hard to modify it to something else. 

For better performance you can use `-d:danger` (it disables all runtime safety checks, so is generally even faster), also try adding `--gc:arc`, `-d:lto` (makes the program compile with LTO, needs lld), or compiling with clang (it's faster than GCC for this program).

### CODE REVIEW

**Comment by ghost** [comment]
Btw, just for some info - I checked the timings with the same range optimization with code from your first commit, and also compiled without `-d:release`, and the time it took was 2.7s (370ms with -d:release).

**Comment by SamWoolerton** [comment]
Wow I really didn't see that coming! Had implemented some algorithm optimisations and tried to avoid copying etc but completely missed the set size (I'm new to low level languages & don't have to think about this in JS etc). Huge perf gains thanks - the larger 10x10 puzzle was crashing before (I think out of memory but didn't say) and now runs in 10s

**Comment by ghost** [comment]
@SamWoolerton nice :) You might also want to try the other flags I've shown in the PR description, at least `-d:danger --gc:arc`, and maybe `-d:lto`

**Comment by SamWoolerton** [comment]
Reckon this would be a good target for `parallel` too? I'm thinking for the `step` function where it generates potential moves and steps through each of them; it's all independent so seems doable, just the [syntax](https://nim-lang.org/docs/manual_experimental.html#parallel-amp-spawn-parallel-statement) is a little funky

**Comment by ghost** [comment]
@SamWoolerton `parallel` in Nim is kind of deprecated, although it will still work (but only with the default GC, not really with ARC). As alternatives you might look into https://github.com/mratsim/weave or https://github.com/status-im/nim-taskpools

**Comment by SamWoolerton** [comment]
> -d:danger --gc:arc

Not gonna lie, the `-d:danger` flag sketches me out a bit. Decent perf gains again though! 8.95s down to 7.75s

**Comment by SamWoolerton** [comment]
> @SamWoolerton `parallel` in Nim is kind of deprecated, although it will still work (but only with the default GC, not really with ARC). As alternatives you might look into https://github.com/mratsim/weave or https://github.com/status-im/nim-taskpools

Great thanks! Will check those out

**Comment by ghost** [comment]
@SamWoolerton for a bit more speedup you can instead of arc actually use `--gc:markAndSweep`, it's not the best GC overall, but it's the best for throughput

**Pull request merged**
